# -*- coding: utf-8 -*-
"""AUTO-GENERATED by tools/riot_dump.py — อย่าแก้มือ (รันสคริปต์ใหม่เมื่อได้ dump แพตช์ใหม่)

ค่าจาก blueprint ของปืนในไฟล์เกม Valorant (dump closed beta เม.ย. 2020) — หน่วยองศา/วินาที
aim/stability.py ใช้ตารางนี้จำลองรีคอยล์/สเปรดแบบเดียวกับระบบ Stability ของเกม
fire rate / damage / mag ของแพตช์ปัจจุบันอยู่ใน aim/guns.py (ตารางนี้ใช้เฉพาะ 'รูปทรง' รีคอยล์)
"""

RIOT = {
 "_source": "Valorant gun blueprint dump (closed beta, Apr 2020) — units: degrees / seconds",
 "_defaults": {
  "stability": {
   "error": [
    [
     0.0,
     0.1
    ],
    [
     1.0,
     0.18
    ],
    [
     2.0,
     0.4
    ],
    [
     3.0,
     0.82
    ],
    [
     4.0,
     1.5
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.75,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     0.10933
    ],
    [
     2.0,
     0.36899
    ],
    [
     3.0,
     0.87464
    ],
    [
     4.0,
     1.70827
    ],
    [
     5.0,
     2.9519
    ],
    [
     6.0,
     4.6875
    ]
   ],
   "pitch_crouch": 1.5,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     4.0,
     0.0
    ],
    [
     8.0,
     1.35
    ],
    [
     16.0,
     1.35
    ],
    [
     19.0,
     -1.35
    ]
   ],
   "yaw_crouch": 1.5,
   "yaw_switch_time": 0.225,
   "error_decay": [
    [
     1.25,
     100.0
    ],
    [
     2.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ]
  },
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.01,
     0.275
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.01,
     0.4
    ],
    [
     1.0,
     0.0
    ]
   ]
  }
 },
 "vandal": {
  "file": "AssaultRifle_AK.json",
  "rps": 9.25,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 25,
  "zooms": [
   1.15
  ],
  "stability": {
   "error": [
    [
     0.0,
     0.25
    ],
    [
     1.0,
     0.3
    ],
    [
     2.0,
     0.35
    ],
    [
     5.0,
     1.0
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.85,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     0.4
    ],
    [
     2.0,
     0.9
    ],
    [
     7.0,
     7.6
    ],
    [
     8.7737,
     7.45539
    ],
    [
     10.48918,
     8.08367
    ],
    [
     12.80231,
     7.53472
    ],
    [
     14.87118,
     8.163
    ],
    [
     17.60838,
     7.77271
    ],
    [
     19.81984,
     8.36219
    ],
    [
     22.20241,
     7.93136
    ]
   ],
   "pitch_crouch": 0.85,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     3.0,
     0.15
    ],
    [
     12.35256,
     2.0
    ],
    [
     14.95311,
     1.9382
    ],
    [
     17.16759,
     2.08101
    ],
    [
     19.30888,
     1.9382
    ],
    [
     21.80809,
     2.11926
    ],
    [
     24.0538,
     1.91981
    ]
   ],
   "yaw_crouch": 1.0,
   "yaw_switch_time": 0.37,
   "error_decay": [
    [
     0.0,
     1000.0
    ],
    [
     0.1,
     40.0
    ],
    [
     1.5,
     10.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 1.0,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "error_ads_mult": 1.15,
   "error_ads_add": -0.13,
   "pitch_ads": 0.7,
   "yaw_ads": 0.7,
   "yaw_switch": 0.07,
   "yaw_switch_crouch": 1.5,
   "yaw_protected": 4.0,
   "recovery": [
    [
     0.0,
     0.025
    ],
    [
     6.0,
     0.4
    ]
   ],
   "gun_recovery": 0.4,
   "tap_eff": 4.0,
   "recoil_increase": 12.0
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.01,
     0.25
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.01,
     0.25
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 5.0,
   "pop_pitch_max": 7.0,
   "pop_yaw_max": 2.0,
   "pop_ads_pitch": 0.8,
   "pop_ads_yaw": 0.8,
   "pitch_to_xhair_alpha": [
    [
     0.0,
     1.0
    ],
    [
     7.0,
     0.0
    ]
   ]
  }
 },
 "phantom": {
  "file": "AssaultRifle_ACR.json",
  "rps": 11.0,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 30,
  "zooms": [
   1.75
  ],
  "stability": {
   "error": [
    [
     0.0,
     0.2
    ],
    [
     1.0,
     0.28
    ],
    [
     2.0,
     0.36
    ],
    [
     4.0,
     0.9
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.85,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     0.3
    ],
    [
     2.0,
     0.7
    ],
    [
     7.0,
     6.4
    ],
    [
     9.08408,
     6.76651
    ],
    [
     12.30117,
     6.47385
    ],
    [
     15.27764,
     6.96297
    ],
    [
     18.20448,
     6.67302
    ],
    [
     21.13132,
     7.12406
    ],
    [
     24.75136,
     6.70524
    ],
    [
     27.90927,
     7.09184
    ]
   ],
   "pitch_crouch": 0.85,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     3.16255,
     0.09201
    ],
    [
     13.0,
     1.8
    ],
    [
     15.56075,
     1.73727
    ],
    [
     18.18806,
     1.83528
    ],
    [
     20.33712,
     1.70311
    ],
    [
     22.00655,
     1.80543
    ],
    [
     24.02462,
     1.699
    ],
    [
     26.21436,
     1.82495
    ],
    [
     28.09278,
     1.71425
    ]
   ],
   "yaw_crouch": 0.85,
   "yaw_switch_time": 0.37,
   "error_decay": [
    [
     0.0,
     1000.0
    ],
    [
     0.1,
     40.0
    ],
    [
     1.5,
     10.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 1.0,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "error_ads_mult": 1.15,
   "error_ads_add": -0.12,
   "pitch_ads": 0.7,
   "yaw_ads": 0.7,
   "yaw_switch": 0.06,
   "yaw_switch_crouch": 1.5,
   "yaw_protected": 4.0,
   "recovery": [
    [
     0.0,
     0.02
    ],
    [
     4.0,
     0.3
    ]
   ],
   "gun_recovery": 0.55,
   "tap_eff": 3.0,
   "instab_per_shot": 0.2,
   "recoil_increase": 12.0
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.01,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.01,
     0.25
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 5.0,
   "pop_yaw_max": 2.0,
   "pop_ads_pitch": 0.8,
   "pop_ads_yaw": 0.8,
   "pitch_to_xhair_alpha": [
    [
     0.0,
     1.0
    ],
    [
     5.75,
     0.0
    ]
   ]
  }
 },
 "sheriff": {
  "file": "RevolverPistol.json",
  "rps": 4.0,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 6,
  "zooms": [],
  "stability": {
   "error": [
    [
     0.0,
     0.25
    ],
    [
     1.0,
     1.1
    ],
    [
     2.0,
     2.75
    ]
   ],
   "error_move": [
    [
     0.0,
     0.25
    ],
    [
     0.62,
     1.5
    ]
   ],
   "error_crouch": 0.75,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     1.0
    ],
    [
     2.0,
     2.0
    ]
   ],
   "pitch_crouch": 1.5,
   "yaw": [
    [
     0.0,
     0.0
    ]
   ],
   "yaw_crouch": 1.5,
   "yaw_switch_time": 0.225,
   "error_decay": [
    [
     0.0,
     10000.0
    ],
    [
     1.0,
     10.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     200.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "yaw_switch": 0.0,
   "recovery": [
    [
     0.0,
     0.025
    ],
    [
     2.0,
     0.25
    ],
    [
     3.0,
     0.5
    ]
   ],
   "gun_recovery": 0.5,
   "tap_eff": 2.0
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     0.5
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     0.25
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 8.0,
   "follow_pitch": 0.8,
   "follow_yaw": 0.8,
   "pop_ads_pitch": 0.5,
   "pop_ads_yaw": 0.5
  }
 },
 "operator": {
  "file": "BoltSniper.json",
  "rps": 0.75,
  "zoom_rps": 0.75,
  "zoom_rps_mult": None,
  "mag": None,
  "zooms": [
   2.5,
   5.0
  ],
  "stability": {
   "error": [
    [
     0.0,
     5.0
    ],
    [
     0.35,
     5.25
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.9,
   "pitch": [
    [
     0.0,
     0.0
    ]
   ],
   "pitch_crouch": 1.5,
   "yaw": [
    [
     0.0,
     0.0
    ]
   ],
   "yaw_crouch": 1.5,
   "yaw_switch_time": 0.225,
   "error_decay": [
    [
     1.25,
     100.0
    ],
    [
     2.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "recovery": [
    [
     0.0,
     0.0
    ]
   ]
  },
  "zoomed_stability": {
   "error": [
    [
     0.0,
     0.0
    ],
    [
     0.25,
     1.0
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.9,
   "pitch": [
    [
     0.0,
     0.0
    ]
   ],
   "pitch_crouch": 1.5,
   "yaw": [
    [
     0.0,
     0.0
    ]
   ],
   "yaw_crouch": 1.5,
   "yaw_switch_time": 0.225,
   "error_decay": [
    [
     1.25,
     100.0
    ],
    [
     2.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "recovery": [
    [
     0.0,
     0.0
    ]
   ]
  },
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     1.25
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     0.75
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 3.0,
   "pop_yaw_min": 0.5
  }
 },
 "bulldog": {
  "file": "AssaultRifle_Burst.json",
  "rps": 9.15,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 24,
  "zooms": [
   1.25
  ],
  "stability": {
   "error": [
    [
     0.0,
     0.1
    ],
    [
     1.0,
     0.18
    ],
    [
     2.0,
     0.4
    ],
    [
     3.0,
     0.82
    ],
    [
     4.0,
     1.5
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.75,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     0.1
    ],
    [
     2.0,
     0.4
    ],
    [
     3.0,
     0.9
    ],
    [
     4.0,
     1.7
    ],
    [
     5.0,
     2.75
    ],
    [
     6.0,
     4.0
    ]
   ],
   "pitch_crouch": 1.0,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     4.0,
     0.0
    ],
    [
     5.0,
     0.6
    ]
   ],
   "yaw_crouch": 1.0,
   "yaw_switch_time": 0.225,
   "error_decay": [
    [
     1.25,
     100.0
    ],
    [
     2.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "yaw_switch": 0.1,
   "recovery": [
    [
     0.0,
     0.0
    ],
    [
     3.0,
     0.4
    ]
   ],
   "gun_recovery": 0.4
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 4.75,
   "pop_ads_pitch": 0.5,
   "pop_ads_yaw": 0.5,
   "pitch_to_xhair_alpha": [
    [
     0.0,
     1.0
    ]
   ]
  }
 },
 "guardian": {
  "file": "DMR.json",
  "rps": 6.5,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 12,
  "zooms": [
   1.75
  ],
  "stability": {
   "error": [
    [
     0.0,
     0.1
    ],
    [
     1.0,
     0.3
    ],
    [
     2.0,
     1.1
    ],
    [
     3.0,
     1.6
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.85,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     0.25
    ],
    [
     2.0,
     1.0
    ],
    [
     6.0,
     5.0
    ]
   ],
   "pitch_crouch": 0.85,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     2.0,
     -0.1
    ],
    [
     7.0,
     -1.25
    ]
   ],
   "yaw_crouch": 0.85,
   "yaw_switch_time": 0.2,
   "error_decay": [
    [
     1.25,
     100.0
    ],
    [
     2.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 1.0,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "error_ads_add": -0.1,
   "yaw_switch": 0.085,
   "yaw_switch_crouch": 1.5,
   "yaw_protected": 3.0,
   "recovery": [
    [
     0.0,
     0.05
    ],
    [
     2.0,
     0.35
    ]
   ],
   "gun_recovery": 0.4,
   "tap_eff": 10.0,
   "recoil_increase": 12.0
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 8.0,
   "pop_pitch_max": 8.0,
   "pop_ads_pitch": 0.8,
   "pop_ads_yaw": 0.8,
   "pitch_to_xhair_alpha": [
    [
     0.0,
     1.0
    ],
    [
     4.0,
     0.0
    ]
   ]
  }
 },
 "spectre": {
  "file": "SubMachineGun_MP5.json",
  "rps": 13.333,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 30,
  "zooms": [],
  "stability": {
   "error": [
    [
     0.0,
     0.4
    ],
    [
     3.0,
     0.85
    ],
    [
     6.0,
     1.2
    ],
    [
     9.0,
     1.5
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.85,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     0.15
    ],
    [
     2.0,
     0.5
    ],
    [
     9.0,
     5.0
    ],
    [
     11.0,
     5.4
    ]
   ],
   "pitch_crouch": 1.25,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     7.0,
     0.0
    ],
    [
     13.0,
     1.25
    ]
   ],
   "yaw_crouch": 1.25,
   "yaw_switch_time": 0.24,
   "error_decay": [
    [
     2.25,
     100.0
    ],
    [
     4.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 1.0,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "error_ads_add": -0.15,
   "yaw_switch": 0.06,
   "yaw_switch_crouch": 1.5,
   "yaw_protected": 7.0,
   "recovery": [
    [
     0.0,
     0.025
    ],
    [
     8.0,
     0.45
    ]
   ],
   "gun_recovery": 0.45,
   "tap_eff": 2.0,
   "recoil_increase": 12.0
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 4.0,
   "pop_ads_pitch": 0.8,
   "pop_ads_yaw": 0.8,
   "pitch_to_xhair_alpha": [
    [
     0.0,
     1.0
    ],
    [
     4.0,
     0.0
    ]
   ]
  }
 },
 "stinger": {
  "file": "Vector.json",
  "rps": 18.0,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 20,
  "zooms": [
   1.25
  ],
  "stability": {
   "error": [
    [
     0.0,
     0.4
    ],
    [
     1.25,
     0.8
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.75,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     2.5,
     1.4
    ]
   ],
   "pitch_crouch": 1.25,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     3.0,
     -0.5
    ]
   ],
   "yaw_crouch": 1.25,
   "yaw_switch_time": 0.23,
   "error_decay": [
    [
     1.25,
     100.0
    ],
    [
     2.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "yaw_switch": 0.1,
   "yaw_protected": 1.0,
   "recovery": [
    [
     0.0,
     0.3
    ],
    [
     4.0,
     0.6
    ],
    [
     8.0,
     0.8
    ]
   ],
   "recoil_increase": 12.0
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.01,
     0.25
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.01,
     0.2
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 4.0,
   "pop_ads_pitch": 0.5,
   "pop_ads_yaw": 0.5
  }
 },
 "classic": {
  "file": "BasePistol.json",
  "rps": 6.75,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 12,
  "zooms": [],
  "stability": {
   "error": [
    [
     0.0,
     1.9
    ],
    [
     0.01,
     2.0
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.75,
   "pitch": [
    [
     0.0,
     0.0
    ]
   ],
   "pitch_crouch": 1.5,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     4.0,
     0.0
    ],
    [
     8.0,
     1.35
    ],
    [
     16.0,
     1.35
    ],
    [
     19.0,
     -1.35
    ]
   ],
   "yaw_crouch": 1.5,
   "yaw_switch_time": 0.225,
   "error_decay": [
    [
     1.25,
     100.0
    ],
    [
     2.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "recovery": [
    [
     0.0,
     0.0
    ],
    [
     0.0,
     0.0
    ]
   ]
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 5.0,
   "follow_pitch": 0.8,
   "follow_yaw": 0.8
  }
 },
 "ghost": {
  "file": "LugerPistol.json",
  "rps": 6.75,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 15,
  "zooms": [],
  "stability": {
   "error": [
    [
     0.0,
     0.3
    ],
    [
     1.0,
     0.65
    ],
    [
     3.0,
     1.65
    ]
   ],
   "error_move": [
    [
     0.0,
     0.0
    ],
    [
     0.26,
     0.25
    ],
    [
     0.62,
     1.85
    ]
   ],
   "error_crouch": 0.75,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     5.0,
     2.0
    ]
   ],
   "pitch_crouch": 1.5,
   "yaw": [
    [
     0.0,
     0.0
    ]
   ],
   "yaw_crouch": 1.5,
   "yaw_switch_time": 0.225,
   "error_decay": [
    [
     0.0,
     10000.0
    ],
    [
     1.0,
     10.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     200.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "yaw_switch": 0.0,
   "recovery": [
    [
     0.0,
     0.025
    ],
    [
     4.0,
     0.3
    ]
   ],
   "gun_recovery": 0.3,
   "tap_eff": 4.0
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 8.0,
   "follow_pitch": 0.8,
   "follow_yaw": 0.8
  }
 },
 "frenzy": {
  "file": "AutomaticPistol.json",
  "rps": None,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 13,
  "zooms": [],
  "stability": {
   "error": [
    [
     0.0,
     0.45
    ],
    [
     1.0,
     0.8
    ],
    [
     5.0,
     1.7
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.85,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     5.0,
     5.5
    ]
   ],
   "pitch_crouch": 1.25,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     2.0,
     0.0
    ],
    [
     5.0,
     1.25
    ]
   ],
   "yaw_crouch": 1.25,
   "yaw_switch_time": 0.25,
   "error_decay": [
    [
     0.0,
     10000.0
    ],
    [
     1.0,
     10.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     200.0
    ]
   ],
   "recoil_decay_add": 1.0,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "yaw_switch_crouch": 1.5,
   "yaw_protected": 4.0,
   "recovery": [
    [
     0.0,
     0.025
    ],
    [
     5.0,
     0.4
    ]
   ],
   "gun_recovery": 0.45,
   "tap_eff": 3.0,
   "recoil_increase": 12.0
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 2.75,
   "pitch_to_xhair_alpha": [
    [
     0.0,
     1.0
    ],
    [
     4.0,
     0.0
    ]
   ]
  }
 },
 "marshal": {
  "file": "LeverSniperRifle.json",
  "rps": 1.5,
  "zoom_rps": 1.2,
  "zoom_rps_mult": None,
  "mag": None,
  "zooms": [],
  "stability": {
   "error": [
    [
     0.0,
     1.0
    ],
    [
     0.05,
     1.25
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.9,
   "pitch": [
    [
     0.0,
     0.0
    ]
   ],
   "pitch_crouch": 1.5,
   "yaw": [
    [
     0.0,
     0.0
    ]
   ],
   "yaw_crouch": 1.5,
   "yaw_switch_time": 0.225,
   "error_decay": [
    [
     1.25,
     100.0
    ],
    [
     2.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "recovery": [
    [
     0.0,
     0.0
    ]
   ]
  },
  "zoomed_stability": {
   "error": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.5
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.9,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     3.0
    ]
   ],
   "pitch_crouch": 1.5,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     1.0
    ]
   ],
   "yaw_crouch": 1.5,
   "yaw_switch_time": 0.225,
   "error_decay": [
    [
     1.25,
     100.0
    ],
    [
     2.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "recovery": [
    [
     0.0,
     0.0
    ]
   ]
  },
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     1.0
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.025,
     0.25
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 3.0
  }
 },
 "ares": {
  "file": "LightMachineGun.json",
  "rps": 10.0,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 50,
  "zooms": [],
  "stability": {
   "error": [
    [
     0.0,
     1.0
    ],
    [
     5.0,
     0.85
    ],
    [
     10.0,
     0.75
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.6,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     15.0,
     6.0
    ],
    [
     24.25341,
     7.87151
    ],
    [
     34.72997,
     9.0
    ],
    [
     40.0,
     11.0
    ],
    [
     48.0,
     12.0
    ]
   ],
   "pitch_crouch": 1.4,
   "yaw": [
    [
     0.2,
     0.0
    ],
    [
     4.0,
     0.0
    ],
    [
     10.0,
     1.5
    ],
    [
     15.0,
     1.85
    ],
    [
     20.0,
     1.95
    ],
    [
     27.69938,
     2.4
    ],
    [
     44.0,
     2.75
    ]
   ],
   "yaw_crouch": 1.4,
   "yaw_switch_time": 0.37,
   "error_decay": [
    [
     2.25,
     100.0
    ],
    [
     4.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 1.0,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "error_ads_mult": 1.15,
   "error_ads_add": -0.25,
   "pitch_ads": 0.7,
   "yaw_ads": 0.7,
   "yaw_switch": 0.06,
   "yaw_switch_crouch": 1.5,
   "yaw_protected": 6.0,
   "recovery": [
    [
     0.0,
     0.025
    ],
    [
     5.0,
     0.65
    ]
   ],
   "gun_recovery": 0.65,
   "tap_eff": 1.0,
   "recoil_increase": 2.0
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.125
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.125
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 6.0,
   "pitch_to_xhair_alpha": [
    [
     0.0,
     1.0
    ],
    [
     5.0,
     0.0
    ]
   ]
  }
 },
 "odin": {
  "file": "HeavyMachineGun.json",
  "rps": 12.0,
  "zoom_rps": 15.6,
  "zoom_rps_mult": None,
  "mag": 100,
  "zooms": [
   1.15
  ],
  "stability": {
   "error": [
    [
     0.0,
     0.8
    ],
    [
     35.0,
     1.1
    ],
    [
     75.0,
     1.3
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.6,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     0.35
    ],
    [
     2.0,
     1.0
    ],
    [
     11.80164,
     8.14394
    ],
    [
     27.38842,
     11.5
    ],
    [
     35.0,
     13.0
    ],
    [
     44.0,
     15.0
    ],
    [
     55.0,
     15.75
    ],
    [
     65.02162,
     16.2
    ],
    [
     75.0,
     17.0
    ]
   ],
   "pitch_crouch": 1.4,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     0.0
    ],
    [
     9.0,
     1.65
    ],
    [
     16.4052,
     1.8
    ],
    [
     25.19514,
     2.5
    ],
    [
     32.06229,
     2.0
    ],
    [
     38.89618,
     2.75
    ],
    [
     47.57351,
     2.6
    ],
    [
     54.02588,
     3.5
    ],
    [
     63.37069,
     3.15
    ],
    [
     70.71304,
     3.75
    ]
   ],
   "yaw_crouch": 1.4,
   "yaw_switch_time": 0.37,
   "error_decay": [
    [
     2.25,
     100.0
    ],
    [
     4.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 1.0,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "error_ads_mult": 1.15,
   "error_ads_add": -0.13,
   "pitch_ads": 0.7,
   "yaw_ads": 0.7,
   "yaw_switch": 0.06,
   "yaw_switch_crouch": 1.5,
   "yaw_protected": 6.0,
   "recovery": [
    [
     0.0,
     0.025
    ],
    [
     6.0,
     0.65
    ]
   ],
   "gun_recovery": 0.65,
   "tap_eff": 1.0,
   "instab_per_shot": 0.05,
   "recoil_increase": 2.0
  },
  "zoomed_stability": {
   "error": [
    [
     0.0,
     0.5
    ],
    [
     75.0,
     4.0
    ]
   ],
   "error_move": [
    [
     0.3,
     0.0
    ],
    [
     0.31,
     2.1
    ],
    [
     0.55,
     2.1
    ],
    [
     0.58,
     4.2
    ]
   ],
   "error_crouch": 0.6,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     10.0,
     1.0
    ]
   ],
   "pitch_crouch": 1.0,
   "yaw": [
    [
     0.0,
     0.0
    ]
   ],
   "yaw_crouch": 1.0,
   "yaw_switch_time": 0.175,
   "error_decay": [
    [
     1.25,
     100.0
    ],
    [
     2.5,
     3.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     2.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "error_ads_mult": 1.15,
   "error_ads_add": -0.13,
   "pitch_ads": 0.7,
   "yaw_ads": 0.7,
   "yaw_switch": 0.025,
   "yaw_switch_crouch": 1.5,
   "yaw_protected": 6.0,
   "recovery": [
    [
     0.0,
     0.1
    ],
    [
     5.0,
     0.65
    ]
   ],
   "gun_recovery": 0.65,
   "tap_eff": 1.0,
   "instab_per_shot": 0.2,
   "recoil_increase": 2.0
  },
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.125
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.125
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 6.5,
   "pitch_to_xhair_alpha": [
    [
     0.0,
     1.0
    ],
    [
     5.0,
     0.0
    ]
   ]
  }
 },
 "bucky": {
  "file": "PumpShotgun.json",
  "rps": 1.1,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 5,
  "zooms": [],
  "stability": {
   "error": [
    [
     0.0,
     3.4
    ]
   ],
   "error_move": [
    [
     0.0,
     0.2
    ]
   ],
   "error_crouch": 0.9,
   "pitch": [
    [
     0.0,
     0.0
    ]
   ],
   "pitch_crouch": 1.5,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     4.0,
     0.0
    ],
    [
     8.0,
     1.35
    ],
    [
     16.0,
     1.35
    ],
    [
     19.0,
     -1.35
    ]
   ],
   "yaw_crouch": 1.5,
   "yaw_switch_time": 0.225,
   "error_decay": [
    [
     0.0,
     10000.0
    ],
    [
     1.0,
     10.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     200.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "recovery": [
    [
     0.0,
     0.01
    ]
   ]
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.01,
     2.75
    ],
    [
     0.25,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.01,
     0.4
    ],
    [
     0.25,
     0.0
    ]
   ],
   "pop_pitch_min": 0.0,
   "follow_pitch": 0.0,
   "follow_yaw": 0.0
  }
 },
 "judge": {
  "file": "AutomaticShotgun.json",
  "rps": 3.5,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 7,
  "zooms": [],
  "stability": {
   "error": [
    [
     0.0,
     2.25
    ],
    [
     1.0,
     3.0
    ],
    [
     2.0,
     3.5
    ],
    [
     3.0,
     4.0
    ]
   ],
   "error_move": [
    [
     0.0,
     0.2
    ]
   ],
   "error_crouch": 0.75,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     3.0,
     5.0
    ],
    [
     4.0,
     6.0
    ],
    [
     6.0,
     5.0
    ],
    [
     7.0,
     6.25
    ]
   ],
   "pitch_crouch": 1.5,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     2.0,
     2.5
    ]
   ],
   "yaw_crouch": 1.5,
   "yaw_switch_time": 0.175,
   "error_decay": [
    [
     0.0,
     10000.0
    ],
    [
     1.0,
     10.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     200.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ],
   "yaw_switch": 0.1,
   "yaw_switch_crouch": 4.0,
   "recovery": [
    [
     0.0,
     0.025
    ],
    [
     4.0,
     0.4
    ]
   ],
   "gun_recovery": 0.4,
   "tap_eff": 4.0
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.15
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_pitch_min": 0.0,
   "follow_pitch": 0.25,
   "follow_yaw": 0.0,
   "pop_ads_pitch": 0.5,
   "pop_ads_yaw": 0.5
  }
 },
 "shorty": {
  "file": "SawedOffShotgun.json",
  "rps": 3.33,
  "zoom_rps": None,
  "zoom_rps_mult": None,
  "mag": 2,
  "zooms": [],
  "stability": {
   "error": [
    [
     0.0,
     4.0
    ],
    [
     0.1,
     4.5
    ]
   ],
   "error_move": [
    [
     0.0,
     0.2
    ]
   ],
   "error_crouch": 0.75,
   "pitch": [
    [
     0.0,
     0.0
    ],
    [
     1.0,
     0.10933
    ],
    [
     2.0,
     0.36899
    ],
    [
     3.0,
     0.87464
    ],
    [
     4.0,
     1.70827
    ],
    [
     5.0,
     2.9519
    ],
    [
     6.0,
     4.6875
    ]
   ],
   "pitch_crouch": 1.5,
   "yaw": [
    [
     0.0,
     0.0
    ],
    [
     4.0,
     0.0
    ],
    [
     8.0,
     1.35
    ],
    [
     16.0,
     1.35
    ],
    [
     19.0,
     -1.35
    ]
   ],
   "yaw_crouch": 1.5,
   "yaw_switch_time": 0.225,
   "error_decay": [
    [
     0.0,
     10000.0
    ],
    [
     1.0,
     10.0
    ]
   ],
   "error_decay_add": 4.0,
   "recoil_decay": [
    [
     0.0,
     200.0
    ]
   ],
   "recoil_decay_add": 0.5,
   "landing": [
    [
     0.0,
     0.5
    ],
    [
     0.2,
     0.0
    ]
   ]
  },
  "zoomed_stability": None,
  "visual": {
   "pop_pitch_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     2.0
    ],
    [
     1.0,
     0.0
    ]
   ],
   "pop_yaw_curve": [
    [
     0.0,
     0.0
    ],
    [
     0.05,
     0.2
    ],
    [
     1.0,
     0.0
    ]
   ],
   "follow_pitch": 0.0,
   "follow_yaw": 0.0
  }
 }
}
